export const AUDIT_ENDPOINTS = {
  QRYABY: { urlA: 'http://docpwk6zafsap:32656/infinity/v1/assetBuy/:id/:type', urlB: 'http://docpwk8zatcap:31401/infinity/v1/assetBuy/:id/:type' },
  QRYSBS: { urlA: 'http://docpwk13zafsap:31889/infinity/v1/subscriptions/:msisdn', urlB: 'http://docpwk13zatcap:31465/infinity/v1/subscriptions/:msisdn' },
  QRYACU: { urlA: 'http://docpwk5zafsap:30899/infinity/v1/customers/:accountId', urlB: 'http://docpwk3zatcap:32529/infinity/v1/customers/:accountId' },
  QRYAST: { urlA: 'http://docpwk13zafsap:32251/infinity/v1/assets/:Id/:type', urlB: 'http://docpwk5zatcap:31077/infinity/v1/assets/:Id/:type' },
  QRYBAH: { urlA: 'http://docpwk7zafsap:32451/infinity/v1/mahbulk', urlB: 'http://docpwk9zatcap:31088/infinity/v1/mahbulk' },
  QRYBAN: { urlA: 'http://docpwk7zafsap:31221/infinity/v1/subscriptions/altNum', urlB: 'http://docpwk1zatcap:32138/infinity/v1/subscriptions/altNum' },
  QRYCAS: { urlA: 'http://docpwk3zafsap:31802/infinity/v1/customerAccount/:type/:id', urlB: 'http://docpwk12zatcap:31474/infinity/v1/customerAccount/:type/:id' },
  QRYCAT: { urlA: 'http://docpwk10zafsap:31584/infinity/v1/customerAccount', urlB: 'http://docpwk7zatcap:31223/infinity/v1/customerAccount' },
  QRYCBD: { urlA: 'http://docpwk11zafsap:31596/infinity/v1/customers/:accountId/billProfiles/:debtorId', urlB: 'http://docpwk6zatcap:32083/infinity/v1/customers/:accountId/billProfiles/:debtorId' },
  QRYCBP: { urlA: 'http://docpwk5zafsap:31564/infinity/v1/customers/:accountId/billProfiles', urlB: 'http://docpwk6zatcap:30118/infinity/v1/customers/:accountId/billProfiles' },
  QRYCNT: { urlA: 'http://docpwk10zafsap:31531/infinity/v1/contact/:id/:type', urlB: 'http://docpwk1zatcap:31019/infinity/v1/contact/:id/:type' },
  QRYCPP: { urlA: 'http://docpwk4zafsap:31197/infinity/v1/customerPrivacyProfile/:msisdn', urlB: 'http://docpwk11zatcap:32619/infinity/v1/customerPrivacyProfile/:msisdn' },
  QRYCPS: { urlA: 'http://docpwk8zafsap:30619/infinity/v1/customerParty/:id', urlB: 'http://docpwk8zatcap:31538/infinity/v1/customerParty/:id' },
  QRYCPY: { urlA: 'http://docpwk6zafsap:30711/infinity/v1/customerParty', urlB: 'http://docpwk7zatcap:30734/infinity/v1/customerParty' },
  QRYCTB: { urlA: 'http://docpwk4zafsap:31667/infinity/v1/customerBill', urlB: 'http://docpwk5zatcap:31135/infinity/v1/customerBill' },
  QRYDBU: { urlA: 'http://docpwk1zafsap:31425/infinity/v1/dbUptime', urlB: 'http://docpwk7zatcap:32569/infinity/v1/dbUptime' },
  QRYDEB: { urlA: 'http://docpwk5zafsap:30612/infinity/v1/debicheck/:id', urlB: 'http://docpwk6zatcap:31656/infinity/v1/debicheck/:id' },
  QRYDLS: { urlA: 'http://docpwk10zafsap:32247/infinity/v1/deals/:id', urlB: 'http://docpwk12zatcap:31387/infinity/v1/deals/:id' },
  QRYEAT: { urlA: 'http://docpwk11zafsap:32009/infinity/v1/:entity/:id/attribute/:name', urlB: 'http://docpwk12zatcap:31672/infinity/v1/:entity/:id/attribute/:name' },
  QRYECC: { urlA: 'http://docpwk7zafsap:31361/infinity/v1/eventRatingEligibility', urlB: 'http://docpwk7zatcap:31763/infinity/v1/eventRatingEligibility' },
  QRYEPO: { urlA: 'http://docpwk12zafsap:31800/infinity/v1/eligibilityProductOffering', urlB: 'http://docpwk10zatcap:31078/infinity/v1/eligibilityProductOffering' },
  QRYINL: { urlA: 'http://docpwk3zafsap:30364/infinity/v1/inventoryList', urlB: 'http://docpwk8zatcap:30241/infinity/v1/inventoryList' },
  QRYINV: { urlA: 'http://docpwk11zafsap:31083/infinity/v1/customerBill/:accountNumber', urlB: 'http://docpwk3zatcap:32452/infinity/v1/customerBill/:accountNumber' },
  QRYMAH: { urlA: 'http://docpwk12zafsap:31579/infinity/v1/mah/:msisdn', urlB: 'http://docpwk4zatcap:32207/infinity/v1/mah/:msisdn' },
  QRYMPR: { urlA: 'http://docpwk13zafsap:30430/infinity/v1/dealsprice', urlB: 'http://docpwk1zatcap:31544/infinity/v1/dealsprice' },
  QRYORH: { urlA: 'http://docpwk7zafsap:32397/infinity/v1/orderHistory/:id', urlB: 'http://docpwk3zatcap:31881/infinity/v1/orderHistory/:id' },
  QRYPDT: { urlA: 'http://docpwk10zafsap:30720/infinity/v1/products/:id/:type/:loginName', urlB: 'http://docpwk3zatcap:31560/infinity/v1/products/:id/:type/:loginName' },
  QRYPOQ: { urlA: 'http://docpwk10zafsap:30739/infinity/v1/productOfferingQualification', urlB: 'http://docpwk6zatcap:31750/infinity/v1/productOfferingQualification' },
  QRYPRD: { urlA: 'http://docpwk11zafsap:30709/infinity/v1/products', urlB: 'http://docpwk8zatcap:30533/infinity/v1/products' },
  QRYPRV: { urlA: 'http://docpwk6zafsap:31255/infinity/v1/mah/:msisdn/privileges', urlB: 'http://docpwk5zatcap:31209/infinity/v1/mah/:msisdn/privileges' },
  QRYRCL: { urlA: 'http://docpwk3zafsap:31540/infinity/v1/repairCentreList', urlB: 'http://docpwk8zatcap:32532/infinity/v1/repairCentreList' },
  QRYROL: { urlA: 'http://docpwk7zafsap:31778/infinity/v1/authRole/:id', urlB: 'http://docpwk11zatcap:30558/infinity/v1/authRole/:id' },
  QRYSAT: { urlA: 'http://docpwk10zafsap:30643/infinity/v1/subscriptions/:msisdn/attribute/:name', urlB: 'http://docpwk8zatcap:30401/infinity/v1/subscriptions/:msisdn/attribute/:name' },
  QRYSBP: { urlA: 'http://docpwk10zafsap:31167/infinity/v1/subscriptions/:msisdn/billProfile', urlB: 'http://docpwk4zatcap:30260/infinity/v1/subscriptions/:msisdn/billProfile' },
  QRYSCU: { urlA: 'http://docpwk13zafsap:31214/infinity/v1/subscriptions/:msisdn/customers', urlB: 'http://docpwk1zatcap:30209/infinity/v1/subscriptions/:msisdn/customers' },
  QRYSCV: { urlA: 'http://docpwk3zafsap:32585/infinity/v1/summaryCustview/:msisdn', urlB: 'http://docpwk11zatcap:32229/infinity/v1/summaryCustview/:msisdn' },
  QRYSHO: { urlA: 'http://docpwk12zafsap:32733/infinity/v1/shippingOrder/:id', urlB: 'http://docpwk11zatcap:31531/infinity/v1/shippingOrder/:id' },
  QRYSKY: { urlA: 'http://docpwk4zafsap:31942/infinity/v1/subscriptionsId/:id', urlB: 'http://docpwk11zatcap:32013/infinity/v1/subscriptionsId/:id' },
  QRYSLN: { urlA: 'http://docpwk4zafsap:31674/infinity/v1/solutions/:contactLogin/:prodId/:servAcctMasterId', urlB: 'http://docpwk5zatcap:31220/infinity/v1/solutions/:contactLogin/:prodId/:servAcctMasterId' },
  QRYSMD: { urlA: 'http://docpwk7zafsap:32602/infinity/v1/msisdn/:id', urlB: 'http://docpwk10zatcap:31628/infinity/v1/msisdn/:id' },
  QRYSOH: { urlA: 'http://docpwk2zafsap:30972/infinity/v1/shippingOrderHist/:id', urlB: 'http://docpwk6zatcap:32632/infinity/v1/shippingOrderHist/:id' },
  QRYSPA: { urlA: 'http://docpwk9zafsap:30894/infinity/v1/subscriptionProfile', urlB: 'http://docpwk4zatcap:31345/infinity/v1/subscriptionProfile' },
  QRYSPC: { urlA: 'http://docpwk5zafsap:32755/infinity/v1/subscriptions/:msisdn/eligibility/:channel/products/:productClass', urlB: 'http://docpwk5zatcap:32605/infinity/v1/subscriptions/:msisdn/eligibility/:channel/products/:productClass' },
  QRYSPF: { urlA: 'http://docpwk9zafsap:31729/infinity/v1/subscriptionProfile/:id', urlB: 'http://docpwk5zatcap:31251/infinity/v1/subscriptionProfile/:id' },
  QRYSPR: { urlA: 'http://docpwk12zafsap:31494/infinity/v1/subscriptions/:msisdn/eligibility/:channel/products', urlB: 'http://docpwk7zatcap:31328/infinity/v1/subscriptions/:msisdn/eligibility/:channel/products' },
  QRYSPS: { urlA: 'http://docpwk9zafsap:31654/infinity/v1/subscriptions/:msisdn/primarySim', urlB: 'http://docpwk8zatcap:30008/infinity/v1/subscriptions/:msisdn/primarySim' },
  QRYSSN: { urlA: 'http://docpwk7zafsap:31753/infinity/v1/subSpecificNeeds/:msisdn', urlB: 'http://docpwk1zatcap:32321/infinity/v1/subSpecificNeeds/:msisdn' },
  QRYSSV: { urlA: 'http://docpwk11zafsap:31820/infinity/v1/subscriptions/:msisdn/services', urlB: 'http://docpwk5zatcap:31406/infinity/v1/subscriptions/:msisdn/services' },
  QRYVAL: { urlA: 'http://docpwk11zafsap:31578/infinity/v1/validateCustomer/:id', urlB: 'http://docpwk11zatcap:31629/infinity/v1/validateCustomer/:id' },
  QRYFNC: { urlA: 'http://docpwk6zafsap:31985/infinity/v1/funeralVariablePricing/:SumAssured/:Channel', urlB: 'http://docpwk3zatcap:32302/infinity/v1/funeralVariablePricing/:SumAssured/:Channel' },
  QRYSSM: { urlA: 'http://docpwk5zafsap:31704/infinity/v1/subscriptions/:msisdn/services', urlB: 'http://docpwk11zatcap:31371/infinity/v1/subscriptions/:msisdn/services' },
  QRYSSP: { urlA: 'http://docpwk4zafsap:30498/infinity/v1/subscriber/:id/specific', urlB: 'http://docpwk9zatcap:30417/infinity/v1/subscriber/:id/specific' },
  QRYINS: { urlA: 'http://docpwk11zafsap:32065/infinity/v1/insuranceVariablePricing/:Msisdn/:DeviceID', urlB: 'http://docpwk5zatcap:30582/infinity/v1/insuranceVariablePricing/:Msisdn/:DeviceID' },
  QRYVET: { urlA: 'http://docpwk11zafsap:31682/infinity/v1/prevetting?id=4310160119086', urlB: 'http://docpwk11zafsap:31682/infinity/v1/prevetting?id=4310160119086' }
  // QRYTEST: { urlA: '/api/v1/audit/test', urlB: '/api/v1/audit/test' }
} as const;


export const AUDIT_TYPES = Object.keys(AUDIT_ENDPOINTS).filter(
  (key) => key !== 'comparison'
) as AuditType[];

export type AuditType = keyof typeof AUDIT_ENDPOINTS;